import type { LucideIcon } from 'lucide-react';
import {
	Home,
	Layers2,
	Landmark,
	Settings,
	CodeXml,
	Puzzle,
	GalleryHorizontalEnd,
	BarChart3,
	Plus,
	CreditCard,
	Receipt,
	FileText,
	Wallet,
	Key,
	UserCog,
	Webhook,
	Rocket,
	BookOpen,
	Mail,
	CalendarDays,
	MessageCircle,
	BotMessageSquare,
	LogOut,
	Keyboard,
	Workflow,
} from 'lucide-react';
import type { CommandPaletteActionIdType } from '@/core/actions';
import { CommandPaletteActionId } from '@/core/actions';

import { CommandPaletteCommandId, type CommandPaletteCommandIdType, CommandPaletteGroup, type CommandPaletteGroupType } from './ids';
import { commandPalettePaths } from './paths';

const DOCS_BASE = 'https://docs.flexprice.io';

export interface CommandPaletteCommand {
	id: CommandPaletteCommandIdType;
	label: string;
	group: CommandPaletteGroupType;
	path?: string;
	/** Open this URL in a new tab (for documentation links). */
	externalUrl?: string;
	/** When set, the organism will look up and run a handler for this id (in addition to optional path). */
	actionId?: CommandPaletteActionIdType;
	keywords?: string[];
	icon?: LucideIcon;
}

const P = commandPalettePaths;

export const commandPaletteCommands: CommandPaletteCommand[] = [
	// Actions (quick create / entry points)
	{
		id: CommandPaletteCommandId.actionCreateFeature,
		label: 'Create Feature',
		group: CommandPaletteGroup.Actions,
		path: P['create-feature'],
		keywords: ['new', 'add', 'feature', 'product'],
		icon: Plus,
	},
	{
		id: CommandPaletteCommandId.actionSimulateIngestEvents,
		label: 'Simulate ingest events',
		group: CommandPaletteGroup.Actions,
		actionId: CommandPaletteActionId.DebugSimulateIngestEvents,
		keywords: ['debug', 'events', 'stream', 'ingest'],
		icon: Rocket,
	},
	// Help (documentation, contact, community)
	{
		id: CommandPaletteCommandId.actionOpenDocumentation,
		label: 'Open documentation',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.OpenDocumentation,
		keywords: ['docs', 'help', 'api', 'developer', 'readme'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.actionKeyboardShortcuts,
		label: 'Keyboard shortcuts',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.ShowKeyboardShortcutsHint,
		keywords: ['shortcuts', 'keys', '⌘K', 'Ctrl+K', 'command palette'],
		icon: Keyboard,
	},
	{
		id: CommandPaletteCommandId.actionContactUs,
		label: 'Contact us',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.ContactUs,
		keywords: ['support', 'email', 'help', 'contact'],
		icon: Mail,
	},
	{
		id: CommandPaletteCommandId.actionBookCall,
		label: 'Book a call',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.BookCall,
		keywords: ['demo', 'calendly', 'schedule', 'meeting'],
		icon: CalendarDays,
	},
	{
		id: CommandPaletteCommandId.actionJoinSlack,
		label: 'Join Slack community',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.JoinSlackCommunity,
		keywords: ['slack', 'community', 'chat', 'support'],
		icon: MessageCircle,
	},
	{
		id: CommandPaletteCommandId.actionOpenIntercom,
		label: 'Open Intercom',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.OpenIntercom,
		keywords: ['chat', 'support', 'messenger', 'help'],
		icon: BotMessageSquare,
	},
	{
		id: CommandPaletteCommandId.actionLogout,
		label: 'Log out',
		group: CommandPaletteGroup.Help,
		actionId: CommandPaletteActionId.Logout,
		keywords: ['sign out', 'signout', 'account', 'exit'],
		icon: LogOut,
	},
	// Documentation (product‑helpful doc links; open in new tab)
	{
		id: CommandPaletteCommandId.docWelcome,
		label: 'Docs: Welcome & overview',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/welcome-to-flexprice`,
		keywords: ['docs', 'welcome', 'intro', 'overview', 'getting started'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreatingMeteredFeature,
		label: 'Docs: Creating a metered feature',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/event-ingestion/creating-a-metered-feature`,
		keywords: ['docs', 'metered', 'feature', 'events', 'usage'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docSendingEvents,
		label: 'Docs: Sending events',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/event-ingestion/sending-events`,
		keywords: ['docs', 'events', 'ingest', 'usage', 'api'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreatingPlan,
		label: 'Docs: Creating a plan',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/product-catalogue/plans/create`,
		keywords: ['docs', 'plan', 'pricing', 'product catalog'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreatingFeature,
		label: 'Docs: Creating a feature',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/product-catalogue/features/create`,
		keywords: ['docs', 'feature', 'product catalog'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreatingCustomer,
		label: 'Docs: Creating a customer',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/customers/create`,
		keywords: ['docs', 'customer', 'billing'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreateSubscription,
		label: 'Docs: Create subscription for customer',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/subscriptions/customers-create-subscription`,
		keywords: ['docs', 'subscription', 'billing', 'customer'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docCreatingWallet,
		label: 'Docs: Creating a wallet',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/wallet/create`,
		keywords: ['docs', 'wallet', 'credits', 'prepaid'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docInvoicesOverview,
		label: 'Docs: Invoices overview',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/invoices/overview`,
		keywords: ['docs', 'invoices', 'billing'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docApiReference,
		label: 'Docs: API Reference',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/api-reference/introduction`,
		keywords: ['docs', 'api', 'reference', 'developer'],
		icon: CodeXml,
	},
	{
		id: CommandPaletteCommandId.docWebhooks,
		label: 'Docs: Webhooks',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/webhook/webhooks`,
		keywords: ['docs', 'webhooks', 'developer'],
		icon: BookOpen,
	},
	{
		id: CommandPaletteCommandId.docApiKeys,
		label: 'Docs: Manage API Keys',
		group: CommandPaletteGroup.Documentation,
		externalUrl: `${DOCS_BASE}/docs/rbac/api`,
		keywords: ['docs', 'api keys', 'rbac', 'developer'],
		icon: BookOpen,
	},
	// Go to - Home
	{
		id: CommandPaletteCommandId.navHome,
		label: 'Home',
		group: CommandPaletteGroup.GoTo,
		path: P['home-dashboard'],
		keywords: ['dashboard', 'overview'],
		icon: Home,
	},
	// Go to - Product Catalog
	{
		id: CommandPaletteCommandId.navProductCatalogFeatures,
		label: 'Product Catalog → Features',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-features'],
		keywords: ['features', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogPlans,
		label: 'Product Catalog → Plans',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-plan'],
		keywords: ['plans', 'pricing', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogCoupons,
		label: 'Product Catalog → Coupons',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-coupons'],
		keywords: ['coupons', 'discounts', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogAddons,
		label: 'Product Catalog → Addons',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-addons'],
		keywords: ['addons', 'add-ons', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogCostSheets,
		label: 'Product Catalog → Cost Sheets',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-cost-sheets'],
		keywords: ['cost sheets', 'costs', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogPriceUnits,
		label: 'Product Catalog → Price Units',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-price-units'],
		keywords: ['price units', 'units', 'product', 'catalog'],
		icon: Layers2,
	},
	{
		id: CommandPaletteCommandId.navProductCatalogGroups,
		label: 'Product Catalog → Groups',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-groups'],
		keywords: ['groups', 'product', 'catalog'],
		icon: Layers2,
	},
	// Go to - Billing
	{
		id: CommandPaletteCommandId.navBillingCustomers,
		label: 'Billing → Customers',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-customers'],
		keywords: ['customers', 'billing', 'accounts'],
		icon: Landmark,
	},
	{
		id: CommandPaletteCommandId.navBillingSubscriptions,
		label: 'Billing → Subscriptions',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-subscriptions'],
		keywords: ['subscriptions', 'billing'],
		icon: CreditCard,
	},
	{
		id: CommandPaletteCommandId.navBillingTaxes,
		label: 'Billing → Taxes',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-taxes'],
		keywords: ['taxes', 'tax rates', 'billing'],
		icon: Landmark,
	},
	{
		id: CommandPaletteCommandId.navBillingInvoices,
		label: 'Billing → Invoices',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-invoices'],
		keywords: ['invoices', 'billing'],
		icon: Receipt,
	},
	{
		id: CommandPaletteCommandId.navBillingCreditNotes,
		label: 'Billing → Credit Notes',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-credit-notes'],
		keywords: ['credit notes', 'credits', 'billing'],
		icon: FileText,
	},
	{
		id: CommandPaletteCommandId.navBillingPayments,
		label: 'Billing → Payments',
		group: CommandPaletteGroup.GoTo,
		path: P['billing-payments'],
		keywords: ['payments', 'billing', 'wallet'],
		icon: Wallet,
	},
	// Go to - Settings
	{
		id: CommandPaletteCommandId.navSettingsBilling,
		label: 'Settings → Billing',
		group: CommandPaletteGroup.GoTo,
		path: P['settings-billing'],
		keywords: ['settings', 'billing', 'payment'],
		icon: Landmark,
	},
	// Go to - Tools
	{
		id: CommandPaletteCommandId.navToolsImports,
		label: 'Tools → Imports',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-bulk-imports'],
		keywords: ['imports', 'bulk import', 'tools'],
		icon: Settings,
	},
	{
		id: CommandPaletteCommandId.navToolsRevenue,
		label: 'Tools → Revenue',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-revenue'],
		keywords: ['revenue', 'dashboard', 'tools'],
		icon: BarChart3,
	},
	{
		id: CommandPaletteCommandId.navToolsExports,
		label: 'Tools → Exports',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-exports'],
		keywords: ['exports', 'tools'],
		icon: Settings,
	},
	{
		id: CommandPaletteCommandId.navToolsS3Exports,
		label: 'Tools → S3 Exports',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-exports-s3'],
		keywords: ['s3', 'exports', 'tools'],
		icon: Settings,
	},
	// Go to - Developers / Usage
	{
		id: CommandPaletteCommandId.navDevelopersEvents,
		label: 'Usage Tracking → Events Debugger',
		group: CommandPaletteGroup.GoTo,
		path: P['usage-tracking-events'],
		keywords: ['events', 'debugger', 'usage', 'developers'],
		icon: CodeXml,
	},
	{
		id: CommandPaletteCommandId.navUsageTrackingQuery,
		label: 'Usage Tracking → Query',
		group: CommandPaletteGroup.GoTo,
		path: P['usage-tracking-query'],
		keywords: ['query', 'usage', 'tracking', 'metrics'],
		icon: CodeXml,
	},
	{
		id: CommandPaletteCommandId.navDevelopersApiKeys,
		label: 'Developers → API Keys',
		group: CommandPaletteGroup.GoTo,
		path: P['developers-api-keys'],
		keywords: ['api keys', 'keys', 'developers'],
		icon: Key,
	},
	{
		id: CommandPaletteCommandId.navDevelopersServiceAccounts,
		label: 'Developers → Service Accounts',
		group: CommandPaletteGroup.GoTo,
		path: P['developers-service-accounts'],
		keywords: ['service accounts', 'developers'],
		icon: UserCog,
	},
	{
		id: CommandPaletteCommandId.navDevelopersWebhooks,
		label: 'Developers → Webhooks',
		group: CommandPaletteGroup.GoTo,
		path: P['developers-webhooks'],
		keywords: ['webhooks', 'developers'],
		icon: Webhook,
	},
	{
		id: CommandPaletteCommandId.navDevelopersWorkflows,
		label: 'Developers → Workflows',
		group: CommandPaletteGroup.GoTo,
		path: P['developers-workflows'],
		keywords: ['workflows', 'temporal', 'runs', 'developers'],
		icon: Workflow,
	},
	// Go to - Integrations & Pricing Widget
	{
		id: CommandPaletteCommandId.navIntegrations,
		label: 'Integrations',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations'],
		keywords: ['integrations', 'tools', 'quickbooks'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationStripe,
		label: 'Integrations → Stripe',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-stripe'],
		keywords: ['stripe', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationRazorpay,
		label: 'Integrations → Razorpay',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-razorpay'],
		keywords: ['razorpay', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationChargebee,
		label: 'Integrations → Chargebee',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-chargebee'],
		keywords: ['chargebee', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationHubspot,
		label: 'Integrations → Hubspot',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-hubspot'],
		keywords: ['hubspot', 'crm', 'sales', 'marketing', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationQuickbooks,
		label: 'Integrations → QuickBooks',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-quickbooks'],
		keywords: ['quickbooks', 'accounting', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationZoho,
		label: 'Integrations → Zoho Books',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-zoho'],
		keywords: ['zoho', 'zoho books', 'accounting', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationNomod,
		label: 'Integrations → Nomod',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-nomod'],
		keywords: ['nomod', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationMoyasar,
		label: 'Integrations → Moyasar',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-moyasar'],
		keywords: ['moyasar', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navIntegrationPaddle,
		label: 'Integrations → Paddle',
		group: CommandPaletteGroup.GoTo,
		path: P['tools-integrations-paddle'],
		keywords: ['paddle', 'payments', 'invoices', 'integrations'],
		icon: Puzzle,
	},
	{
		id: CommandPaletteCommandId.navPricingWidget,
		label: 'Pricing Widget',
		group: CommandPaletteGroup.GoTo,
		path: P['product-catalog-pricing-widget'],
		keywords: ['pricing', 'widget', 'embed'],
		icon: GalleryHorizontalEnd,
	},
];
